// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pam

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConversation creates a new instance of MockConversation. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConversation(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConversation {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockConversation{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockConversation is an autogenerated mock type for the Conversation type
type MockConversation struct {
	mock.Mock
}

type MockConversation_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConversation) EXPECT() *MockConversation_Expecter {
	return &MockConversation_Expecter{mock: &_m.Mock}
}

// Respond provides a mock function for the type MockConversation
func (_mock *MockConversation) Respond(message Message, answer []byte) (int, error) {
	ret := _mock.Called(message, answer)

	if len(ret) == 0 {
		panic("no return value specified for Respond")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(Message, []byte) (int, error)); ok {
		return returnFunc(message, answer)
	}
	if returnFunc, ok := ret.Get(0).(func(Message, []byte) int); ok {
		r0 = returnFunc(message, answer)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(Message, []byte) error); ok {
		r1 = returnFunc(message, answer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConversation_Respond_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Respond'
type MockConversation_Respond_Call struct {
	*mock.Call
}

// Respond is a helper method to define mock.On call
//   - message Message
//   - answer []byte
func (_e *MockConversation_Expecter) Respond(message any, answer any) *MockConversation_Respond_Call {
	return &MockConversation_Respond_Call{Call: _e.mock.On("Respond", message, answer)}
}

func (_c *MockConversation_Respond_Call) Run(run func(message Message, answer []byte)) *MockConversation_Respond_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Message
		if args[0] != nil {
			arg0 = args[0].(Message)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConversation_Respond_Call) Return(n int, err error) *MockConversation_Respond_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockConversation_Respond_Call) RunAndReturn(run func(message Message, answer []byte) (int, error)) *MockConversation_Respond_Call {
	_c.Call.Return(run)
	return _c
}
