// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pam

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// newMocklibraryFunctions creates a new instance of mocklibraryFunctions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocklibraryFunctions(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocklibraryFunctions {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mocklibraryFunctions{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mocklibraryFunctions is an autogenerated mock type for the libraryFunctions type
type mocklibraryFunctions struct {
	mock.Mock
}

type mocklibraryFunctions_Expecter struct {
	mock *mock.Mock
}

func (_m *mocklibraryFunctions) EXPECT() *mocklibraryFunctions_Expecter {
	return &mocklibraryFunctions_Expecter{mock: &_m.Mock}
}

// AcctMgmt provides a mock function for the type mocklibraryFunctions
func (_mock *mocklibraryFunctions) AcctMgmt(handle unsafe.Pointer, flags Flags) Status {
	ret := _mock.Called(handle, flags)

	if len(ret) == 0 {
		panic("no return value specified for AcctMgmt")
	}

	var r0 Status
	if returnFunc, ok := ret.Get(0).(func(unsafe.Pointer, Flags) Status); ok {
		r0 = returnFunc(handle, flags)
	} else {
		r0 = ret.Get(0).(Status)
	}
	return r0
}

// mocklibraryFunctions_AcctMgmt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcctMgmt'
type mocklibraryFunctions_AcctMgmt_Call struct {
	*mock.Call
}

// AcctMgmt is a helper method to define mock.On call
//   - handle unsafe.Pointer
//   - flags Flags
func (_e *mocklibraryFunctions_Expecter) AcctMgmt(handle any, flags any) *mocklibraryFunctions_AcctMgmt_Call {
	return &mocklibraryFunctions_AcctMgmt_Call{Call: _e.mock.On("AcctMgmt", handle, flags)}
}

func (_c *mocklibraryFunctions_AcctMgmt_Call) Run(run func(handle unsafe.Pointer, flags Flags)) *mocklibraryFunctions_AcctMgmt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 unsafe.Pointer
		if args[0] != nil {
			arg0 = args[0].(unsafe.Pointer)
		}
		var arg1 Flags
		if args[1] != nil {
			arg1 = args[1].(Flags)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocklibraryFunctions_AcctMgmt_Call) Return(status Status) *mocklibraryFunctions_AcctMgmt_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *mocklibraryFunctions_AcctMgmt_Call) RunAndReturn(run func(handle unsafe.Pointer, flags Flags) Status) *mocklibraryFunctions_AcctMgmt_Call {
	_c.Call.Return(run)
	return _c
}

// Authenticate provides a mock function for the type mocklibraryFunctions
func (_mock *mocklibraryFunctions) Authenticate(handle unsafe.Pointer, flags Flags) Status {
	ret := _mock.Called(handle, flags)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 Status
	if returnFunc, ok := ret.Get(0).(func(unsafe.Pointer, Flags) Status); ok {
		r0 = returnFunc(handle, flags)
	} else {
		r0 = ret.Get(0).(Status)
	}
	return r0
}

// mocklibraryFunctions_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type mocklibraryFunctions_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - handle unsafe.Pointer
//   - flags Flags
func (_e *mocklibraryFunctions_Expecter) Authenticate(handle any, flags any) *mocklibraryFunctions_Authenticate_Call {
	return &mocklibraryFunctions_Authenticate_Call{Call: _e.mock.On("Authenticate", handle, flags)}
}

func (_c *mocklibraryFunctions_Authenticate_Call) Run(run func(handle unsafe.Pointer, flags Flags)) *mocklibraryFunctions_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 unsafe.Pointer
		if args[0] != nil {
			arg0 = args[0].(unsafe.Pointer)
		}
		var arg1 Flags
		if args[1] != nil {
			arg1 = args[1].(Flags)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocklibraryFunctions_Authenticate_Call) Return(status Status) *mocklibraryFunctions_Authenticate_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *mocklibraryFunctions_Authenticate_Call) RunAndReturn(run func(handle unsafe.Pointer, flags Flags) Status) *mocklibraryFunctions_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// End provides a mock function for the type mocklibraryFunctions
func (_mock *mocklibraryFunctions) End(handle unsafe.Pointer, status Status) Status {
	ret := _mock.Called(handle, status)

	if len(ret) == 0 {
		panic("no return value specified for End")
	}

	var r0 Status
	if returnFunc, ok := ret.Get(0).(func(unsafe.Pointer, Status) Status); ok {
		r0 = returnFunc(handle, status)
	} else {
		r0 = ret.Get(0).(Status)
	}
	return r0
}

// mocklibraryFunctions_End_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'End'
type mocklibraryFunctions_End_Call struct {
	*mock.Call
}

// End is a helper method to define mock.On call
//   - handle unsafe.Pointer
//   - status Status
func (_e *mocklibraryFunctions_Expecter) End(handle any, status any) *mocklibraryFunctions_End_Call {
	return &mocklibraryFunctions_End_Call{Call: _e.mock.On("End", handle, status)}
}

func (_c *mocklibraryFunctions_End_Call) Run(run func(handle unsafe.Pointer, status Status)) *mocklibraryFunctions_End_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 unsafe.Pointer
		if args[0] != nil {
			arg0 = args[0].(unsafe.Pointer)
		}
		var arg1 Status
		if args[1] != nil {
			arg1 = args[1].(Status)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocklibraryFunctions_End_Call) Return(status1 Status) *mocklibraryFunctions_End_Call {
	_c.Call.Return(status1)
	return _c
}

func (_c *mocklibraryFunctions_End_Call) RunAndReturn(run func(handle unsafe.Pointer, status Status) Status) *mocklibraryFunctions_End_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type mocklibraryFunctions
func (_mock *mocklibraryFunctions) Start(service unsafe.Pointer, user unsafe.Pointer, conversation unsafe.Pointer, output unsafe.Pointer) Status {
	ret := _mock.Called(service, user, conversation, output)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 Status
	if returnFunc, ok := ret.Get(0).(func(unsafe.Pointer, unsafe.Pointer, unsafe.Pointer, unsafe.Pointer) Status); ok {
		r0 = returnFunc(service, user, conversation, output)
	} else {
		r0 = ret.Get(0).(Status)
	}
	return r0
}

// mocklibraryFunctions_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type mocklibraryFunctions_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - service unsafe.Pointer
//   - user unsafe.Pointer
//   - conversation unsafe.Pointer
//   - output unsafe.Pointer
func (_e *mocklibraryFunctions_Expecter) Start(service any, user any, conversation any, output any) *mocklibraryFunctions_Start_Call {
	return &mocklibraryFunctions_Start_Call{Call: _e.mock.On("Start", service, user, conversation, output)}
}

func (_c *mocklibraryFunctions_Start_Call) Run(run func(service unsafe.Pointer, user unsafe.Pointer, conversation unsafe.Pointer, output unsafe.Pointer)) *mocklibraryFunctions_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 unsafe.Pointer
		if args[0] != nil {
			arg0 = args[0].(unsafe.Pointer)
		}
		var arg1 unsafe.Pointer
		if args[1] != nil {
			arg1 = args[1].(unsafe.Pointer)
		}
		var arg2 unsafe.Pointer
		if args[2] != nil {
			arg2 = args[2].(unsafe.Pointer)
		}
		var arg3 unsafe.Pointer
		if args[3] != nil {
			arg3 = args[3].(unsafe.Pointer)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mocklibraryFunctions_Start_Call) Return(status Status) *mocklibraryFunctions_Start_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *mocklibraryFunctions_Start_Call) RunAndReturn(run func(service unsafe.Pointer, user unsafe.Pointer, conversation unsafe.Pointer, output unsafe.Pointer) Status) *mocklibraryFunctions_Start_Call {
	_c.Call.Return(run)
	return _c
}
