// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pam

import (
	"unsafe"

	mock "github.com/stretchr/testify/mock"
)

// newMocknativeMemory creates a new instance of mocknativeMemory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocknativeMemory(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocknativeMemory {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mocknativeMemory{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mocknativeMemory is an autogenerated mock type for the nativeMemory type
type mocknativeMemory struct {
	mock.Mock
}

type mocknativeMemory_Expecter struct {
	mock *mock.Mock
}

func (_m *mocknativeMemory) EXPECT() *mocknativeMemory_Expecter {
	return &mocknativeMemory_Expecter{mock: &_m.Mock}
}

// alloc provides a mock function for the type mocknativeMemory
func (_mock *mocknativeMemory) alloc(size uintptr) (unsafe.Pointer, error) {
	ret := _mock.Called(size)

	if len(ret) == 0 {
		panic("no return value specified for alloc")
	}

	var r0 unsafe.Pointer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uintptr) (unsafe.Pointer, error)); ok {
		return returnFunc(size)
	}
	if returnFunc, ok := ret.Get(0).(func(uintptr) unsafe.Pointer); ok {
		r0 = returnFunc(size)
	} else {
		r0 = ret.Get(0).(unsafe.Pointer)
	}
	if returnFunc, ok := ret.Get(1).(func(uintptr) error); ok {
		r1 = returnFunc(size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocknativeMemory_alloc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'alloc'
type mocknativeMemory_alloc_Call struct {
	*mock.Call
}

// alloc is a helper method to define mock.On call
//   - size uintptr
func (_e *mocknativeMemory_Expecter) alloc(size any) *mocknativeMemory_alloc_Call {
	return &mocknativeMemory_alloc_Call{Call: _e.mock.On("alloc", size)}
}

func (_c *mocknativeMemory_alloc_Call) Run(run func(size uintptr)) *mocknativeMemory_alloc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uintptr
		if args[0] != nil {
			arg0 = args[0].(uintptr)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocknativeMemory_alloc_Call) Return(v unsafe.Pointer, err error) *mocknativeMemory_alloc_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *mocknativeMemory_alloc_Call) RunAndReturn(run func(size uintptr) (unsafe.Pointer, error)) *mocknativeMemory_alloc_Call {
	_c.Call.Return(run)
	return _c
}

// free provides a mock function for the type mocknativeMemory
func (_mock *mocknativeMemory) free(pointer unsafe.Pointer) {
	_mock.Called(pointer)
	return
}

// mocknativeMemory_free_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'free'
type mocknativeMemory_free_Call struct {
	*mock.Call
}

// free is a helper method to define mock.On call
//   - pointer unsafe.Pointer
func (_e *mocknativeMemory_Expecter) free(pointer any) *mocknativeMemory_free_Call {
	return &mocknativeMemory_free_Call{Call: _e.mock.On("free", pointer)}
}

func (_c *mocknativeMemory_free_Call) Run(run func(pointer unsafe.Pointer)) *mocknativeMemory_free_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 unsafe.Pointer
		if args[0] != nil {
			arg0 = args[0].(unsafe.Pointer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocknativeMemory_free_Call) Return() *mocknativeMemory_free_Call {
	_c.Call.Return()
	return _c
}

func (_c *mocknativeMemory_free_Call) RunAndReturn(run func(pointer unsafe.Pointer)) *mocknativeMemory_free_Call {
	_c.Run(run)
	return _c
}
